export const ROUTES = {
    main: '/',
    auth: '/auth',
    registration: '/registration',
    recovery: '/forgot-pass',
    profile: '/profile',
    allCategories: '/books/all',
    bookCategory: '/books/:category',
    terms: '/terms',
    contract: '/contract',
    bookDetail: '/books/:category/:bookId',
    admin: '/admin',
    adminBooks: '/admin/books',
    adminUsers: '/admin/users',
    adminUser: '/admin/users/:userId',
};
